### ISSUE TITLE
Win32 clipboard trying to import on Linux

### ISSUE THREAD

**Issue by joedborg** [pyreadline/pyreadline#13]
After installing with `./setup.py install`, I get this message when trying to import:

OpenClipboard = windll.user32.OpenClipboard
NameError: name 'windll' is not defined

Is there a way to force the setup to install Linux arch instead of Windows?

**Comment by jstenar** [comment]
PR #36 adds platform check that raise an exception when installing or importing on non-windows systems.

**Comment by mishagr** [comment]
Hi,
I've implemented Linux (and darwin) support for pyreadline using ANSI sequences.
It is missing some functionality like copy-paste also there may be some problems with certain terminals, but nevertheless basic functionality is supported.
The clone with linux support is available here https://github.com/mishagr/pyreadline
Pyreadline with linux support allows easy cross-platform development and its linux implementation should work seamlessly with any python interpreter, e.g. PyPy.
I wonder if this implementation is of enough interest for the general public/jstenar to make the effort for integrating the changes to the main repository.

**Comment by takluyver** [comment]
I suspect there is not enough interest:
- Pyreadline is more or less unmaintained now.
- IPython, which I think has so far been the main package requiring pyreadline on Windows, is moving away from readline entirely in favour of prompt_toolkit, which is pure Python and cross platform.
- PyPy has its own pure Python readline-like package, [pyrepl](https://bitbucket.org/pypy/pyrepl/).

Impressive job, though ;-)
